// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package generated

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ExampleDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cost": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"metric": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"value": schema.StringAttribute{
								Computed: true,
							},
						},
						CustomType: MetricType{
							ObjectType: types.ObjectType{
								AttrTypes: MetricValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: CostType{
					ObjectType: types.ObjectType{
						AttrTypes: CostValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"daily_coverage": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"compute": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"on_demand_cost": schema.Float64Attribute{
								Computed: true,
							},
						},
						CustomType: ComputeType{
							ObjectType: types.ObjectType{
								AttrTypes: ComputeValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: DailyCoverageType{
					ObjectType: types.ObjectType{
						AttrTypes: DailyCoverageValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"onboarding_status": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"compute": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"status": schema.StringAttribute{
								Computed: true,
							},
						},
						CustomType: OnboardingStatusComputeType{
							ObjectType: types.ObjectType{
								AttrTypes: OnboardingStatusComputeValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: OnboardingStatusType{
					ObjectType: types.ObjectType{
						AttrTypes: OnboardingStatusValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"savings_totals": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"compute": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"lifetime": schema.SingleNestedAttribute{
								Attributes: map[string]schema.Attribute{
									"amount": schema.Float64Attribute{
										Computed: true,
									},
								},
								CustomType: LifetimeType{
									ObjectType: types.ObjectType{
										AttrTypes: LifetimeValue{}.AttributeTypes(ctx),
									},
								},
								Computed: true,
							},
						},
						CustomType: SavingsTotalsComputeType{
							ObjectType: types.ObjectType{
								AttrTypes: SavingsTotalsComputeValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: SavingsTotalsType{
					ObjectType: types.ObjectType{
						AttrTypes: SavingsTotalsValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"usage": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"metric": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"value": schema.StringAttribute{
								Computed: true,
							},
						},
						CustomType: MetricType{
							ObjectType: types.ObjectType{
								AttrTypes: MetricValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: UsageType{
					ObjectType: types.ObjectType{
						AttrTypes: UsageValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type ExampleModel struct {
	Cost             CostValue             `tfsdk:"cost"`
	DailyCoverage    DailyCoverageValue    `tfsdk:"daily_coverage"`
	OnboardingStatus OnboardingStatusValue `tfsdk:"onboarding_status"`
	SavingsTotals    SavingsTotalsValue    `tfsdk:"savings_totals"`
	Usage            UsageValue            `tfsdk:"usage"`
}

var _ basetypes.ObjectTypable = CostType{}

type CostType struct {
	basetypes.ObjectType
}

func (t CostType) Equal(o attr.Type) bool {
	other, ok := o.(CostType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CostType) String() string {
	return "CostType"
}

func (t CostType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewCostValueNull(), diags
	}

	if in.IsUnknown() {
		return NewCostValueUnknown(), diags
	}

	attributes := in.Attributes()

	metricAttribute, ok := attributes["metric"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`metric is missing from object`)

		return nil, diags
	}

	metricValuable, ok := metricAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`metric expected to be basetypes.ObjectValuable, was: %T`, metricAttribute))

		return nil, diags
	}

	metricObjVal, metricObjValDiags := metricValuable.ToObjectValue(ctx)
	diags.Append(metricObjValDiags...)

	metricTypable, ok := t.AttrTypes["metric"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`metric expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["metric"]))

		return nil, diags
	}

	metricConverted, metricConvertedDiags := metricTypable.ValueFromObject(ctx, metricObjVal)
	diags.Append(metricConvertedDiags...)

	metricVal, ok := metricConverted.(MetricValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`metric expected to be MetricValue, was: %T`, metricConverted))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CostValue{
		Metric: metricVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewCostValueNull() CostValue {
	return CostValue{
		state: attr.ValueStateNull,
	}
}

func NewCostValueUnknown() CostValue {
	return CostValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCostValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CostValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CostValue Attribute Value",
				"While creating a CostValue value, a missing attribute value was detected. "+
					"A CostValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CostValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CostValue Attribute Type",
				"While creating a CostValue value, an invalid attribute value was detected. "+
					"A CostValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CostValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CostValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CostValue Attribute Value",
				"While creating a CostValue value, an extra attribute value was detected. "+
					"A CostValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CostValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCostValueUnknown(), diags
	}

	metricAttribute, ok := attributes["metric"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`metric is missing from object`)

		return NewCostValueUnknown(), diags
	}

	metricVal, ok := metricAttribute.(MetricValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`metric expected to be MetricValue, was: %T`, metricAttribute))
	}

	if diags.HasError() {
		return NewCostValueUnknown(), diags
	}

	return CostValue{
		Metric: metricVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewCostValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CostValue {
	object, diags := NewCostValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCostValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CostType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCostValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCostValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCostValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCostValueMust(CostValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CostType) ValueType(ctx context.Context) attr.Value {
	return CostValue{}
}

var _ basetypes.ObjectValuable = CostValue{}

type CostValue struct {
	Metric MetricValue `tfsdk:"metric"`
	state  attr.ValueState
}

func (v CostValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["metric"] = MetricType{
		basetypes.ObjectType{
			AttrTypes: MetricValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Metric.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["metric"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CostValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CostValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CostValue) String() string {
	return "CostValue"
}

func (v CostValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var metric attr.Value

	{
		metric = v.Metric
	}

	attributeTypes := map[string]attr.Type{
		"metric": MetricType{
			basetypes.ObjectType{
				AttrTypes: MetricValue{}.AttributeTypes(ctx),
			},
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"metric": metric,
		})

	return objVal, diags
}

func (v CostValue) Equal(o attr.Value) bool {
	other, ok := o.(CostValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Metric.Equal(other.Metric) {
		return false
	}

	return true
}

func (v CostValue) Type(ctx context.Context) attr.Type {
	return CostType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CostValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"metric": MetricType{
			basetypes.ObjectType{
				AttrTypes: MetricValue{}.AttributeTypes(ctx),
			},
		},
	}
}

var _ basetypes.ObjectTypable = MetricType{}

type MetricType struct {
	basetypes.ObjectType
}

func (t MetricType) Equal(o attr.Type) bool {
	other, ok := o.(MetricType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MetricType) String() string {
	return "MetricType"
}

func (t MetricType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewMetricValueNull(), diags
	}

	if in.IsUnknown() {
		return NewMetricValueUnknown(), diags
	}

	attributes := in.Attributes()

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MetricValue{
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetricValueNull() MetricValue {
	return MetricValue{
		state: attr.ValueStateNull,
	}
}

func NewMetricValueUnknown() MetricValue {
	return MetricValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMetricValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MetricValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MetricValue Attribute Value",
				"While creating a MetricValue value, a missing attribute value was detected. "+
					"A MetricValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetricValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MetricValue Attribute Type",
				"While creating a MetricValue value, an invalid attribute value was detected. "+
					"A MetricValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MetricValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MetricValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MetricValue Attribute Value",
				"While creating a MetricValue value, an extra attribute value was detected. "+
					"A MetricValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MetricValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMetricValueUnknown(), diags
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewMetricValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return NewMetricValueUnknown(), diags
	}

	return MetricValue{
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewMetricValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MetricValue {
	object, diags := NewMetricValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMetricValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MetricType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMetricValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMetricValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMetricValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMetricValueMust(MetricValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MetricType) ValueType(ctx context.Context) attr.Value {
	return MetricValue{}
}

var _ basetypes.ObjectValuable = MetricValue{}

type MetricValue struct {
	Value basetypes.StringValue `tfsdk:"value"`
	state attr.ValueState
}

func (v MetricValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MetricValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MetricValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MetricValue) String() string {
	return "MetricValue"
}

func (v MetricValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"value": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"value": v.Value,
		})

	return objVal, diags
}

func (v MetricValue) Equal(o attr.Value) bool {
	other, ok := o.(MetricValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v MetricValue) Type(ctx context.Context) attr.Type {
	return MetricType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MetricValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"value": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = DailyCoverageType{}

type DailyCoverageType struct {
	basetypes.ObjectType
}

func (t DailyCoverageType) Equal(o attr.Type) bool {
	other, ok := o.(DailyCoverageType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DailyCoverageType) String() string {
	return "DailyCoverageType"
}

func (t DailyCoverageType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewDailyCoverageValueNull(), diags
	}

	if in.IsUnknown() {
		return NewDailyCoverageValueUnknown(), diags
	}

	attributes := in.Attributes()

	computeAttribute, ok := attributes["compute"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`compute is missing from object`)

		return nil, diags
	}

	computeValuable, ok := computeAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected to be basetypes.ObjectValuable, was: %T`, computeAttribute))

		return nil, diags
	}

	computeObjVal, computeObjValDiags := computeValuable.ToObjectValue(ctx)
	diags.Append(computeObjValDiags...)

	computeTypable, ok := t.AttrTypes["compute"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["compute"]))

		return nil, diags
	}

	computeConverted, computeConvertedDiags := computeTypable.ValueFromObject(ctx, computeObjVal)
	diags.Append(computeConvertedDiags...)

	computeVal, ok := computeConverted.(ComputeValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected to be ComputeValue, was: %T`, computeConverted))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DailyCoverageValue{
		Compute: computeVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewDailyCoverageValueNull() DailyCoverageValue {
	return DailyCoverageValue{
		state: attr.ValueStateNull,
	}
}

func NewDailyCoverageValueUnknown() DailyCoverageValue {
	return DailyCoverageValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDailyCoverageValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DailyCoverageValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DailyCoverageValue Attribute Value",
				"While creating a DailyCoverageValue value, a missing attribute value was detected. "+
					"A DailyCoverageValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DailyCoverageValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DailyCoverageValue Attribute Type",
				"While creating a DailyCoverageValue value, an invalid attribute value was detected. "+
					"A DailyCoverageValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DailyCoverageValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DailyCoverageValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DailyCoverageValue Attribute Value",
				"While creating a DailyCoverageValue value, an extra attribute value was detected. "+
					"A DailyCoverageValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DailyCoverageValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDailyCoverageValueUnknown(), diags
	}

	computeAttribute, ok := attributes["compute"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`compute is missing from object`)

		return NewDailyCoverageValueUnknown(), diags
	}

	computeVal, ok := computeAttribute.(ComputeValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected to be ComputeValue, was: %T`, computeAttribute))
	}

	if diags.HasError() {
		return NewDailyCoverageValueUnknown(), diags
	}

	return DailyCoverageValue{
		Compute: computeVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewDailyCoverageValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DailyCoverageValue {
	object, diags := NewDailyCoverageValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDailyCoverageValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DailyCoverageType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDailyCoverageValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDailyCoverageValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDailyCoverageValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDailyCoverageValueMust(DailyCoverageValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DailyCoverageType) ValueType(ctx context.Context) attr.Value {
	return DailyCoverageValue{}
}

var _ basetypes.ObjectValuable = DailyCoverageValue{}

type DailyCoverageValue struct {
	Compute ComputeValue `tfsdk:"compute"`
	state   attr.ValueState
}

func (v DailyCoverageValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["compute"] = ComputeType{
		basetypes.ObjectType{
			AttrTypes: ComputeValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Compute.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["compute"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DailyCoverageValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DailyCoverageValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DailyCoverageValue) String() string {
	return "DailyCoverageValue"
}

func (v DailyCoverageValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var compute attr.Value

	{
		compute = v.Compute
	}

	attributeTypes := map[string]attr.Type{
		"compute": ComputeType{
			basetypes.ObjectType{
				AttrTypes: ComputeValue{}.AttributeTypes(ctx),
			},
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"compute": compute,
		})

	return objVal, diags
}

func (v DailyCoverageValue) Equal(o attr.Value) bool {
	other, ok := o.(DailyCoverageValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Compute.Equal(other.Compute) {
		return false
	}

	return true
}

func (v DailyCoverageValue) Type(ctx context.Context) attr.Type {
	return DailyCoverageType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DailyCoverageValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"compute": ComputeType{
			basetypes.ObjectType{
				AttrTypes: ComputeValue{}.AttributeTypes(ctx),
			},
		},
	}
}

var _ basetypes.ObjectTypable = ComputeType{}

type ComputeType struct {
	basetypes.ObjectType
}

func (t ComputeType) Equal(o attr.Type) bool {
	other, ok := o.(ComputeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ComputeType) String() string {
	return "ComputeType"
}

func (t ComputeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewComputeValueNull(), diags
	}

	if in.IsUnknown() {
		return NewComputeValueUnknown(), diags
	}

	attributes := in.Attributes()

	onDemandCostAttribute, ok := attributes["on_demand_cost"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`on_demand_cost is missing from object`)

		return nil, diags
	}

	onDemandCostVal, ok := onDemandCostAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`on_demand_cost expected to be basetypes.Float64Value, was: %T`, onDemandCostAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ComputeValue{
		OnDemandCost: onDemandCostVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewComputeValueNull() ComputeValue {
	return ComputeValue{
		state: attr.ValueStateNull,
	}
}

func NewComputeValueUnknown() ComputeValue {
	return ComputeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewComputeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ComputeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ComputeValue Attribute Value",
				"While creating a ComputeValue value, a missing attribute value was detected. "+
					"A ComputeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ComputeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ComputeValue Attribute Type",
				"While creating a ComputeValue value, an invalid attribute value was detected. "+
					"A ComputeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ComputeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ComputeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ComputeValue Attribute Value",
				"While creating a ComputeValue value, an extra attribute value was detected. "+
					"A ComputeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ComputeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewComputeValueUnknown(), diags
	}

	onDemandCostAttribute, ok := attributes["on_demand_cost"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`on_demand_cost is missing from object`)

		return NewComputeValueUnknown(), diags
	}

	onDemandCostVal, ok := onDemandCostAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`on_demand_cost expected to be basetypes.Float64Value, was: %T`, onDemandCostAttribute))
	}

	if diags.HasError() {
		return NewComputeValueUnknown(), diags
	}

	return ComputeValue{
		OnDemandCost: onDemandCostVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewComputeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ComputeValue {
	object, diags := NewComputeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewComputeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ComputeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewComputeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewComputeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewComputeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewComputeValueMust(ComputeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ComputeType) ValueType(ctx context.Context) attr.Value {
	return ComputeValue{}
}

var _ basetypes.ObjectValuable = ComputeValue{}

type ComputeValue struct {
	OnDemandCost basetypes.Float64Value `tfsdk:"on_demand_cost"`
	state        attr.ValueState
}

func (v ComputeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["on_demand_cost"] = basetypes.Float64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.OnDemandCost.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["on_demand_cost"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ComputeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ComputeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ComputeValue) String() string {
	return "ComputeValue"
}

func (v ComputeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"on_demand_cost": basetypes.Float64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"on_demand_cost": v.OnDemandCost,
		})

	return objVal, diags
}

func (v ComputeValue) Equal(o attr.Value) bool {
	other, ok := o.(ComputeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.OnDemandCost.Equal(other.OnDemandCost) {
		return false
	}

	return true
}

func (v ComputeValue) Type(ctx context.Context) attr.Type {
	return ComputeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ComputeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"on_demand_cost": basetypes.Float64Type{},
	}
}

var _ basetypes.ObjectTypable = OnboardingStatusType{}

type OnboardingStatusType struct {
	basetypes.ObjectType
}

func (t OnboardingStatusType) Equal(o attr.Type) bool {
	other, ok := o.(OnboardingStatusType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OnboardingStatusType) String() string {
	return "OnboardingStatusType"
}

func (t OnboardingStatusType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewOnboardingStatusValueNull(), diags
	}

	if in.IsUnknown() {
		return NewOnboardingStatusValueUnknown(), diags
	}

	attributes := in.Attributes()

	computeAttribute, ok := attributes["compute"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`compute is missing from object`)

		return nil, diags
	}

	computeValuable, ok := computeAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected to be basetypes.ObjectValuable, was: %T`, computeAttribute))

		return nil, diags
	}

	computeObjVal, computeObjValDiags := computeValuable.ToObjectValue(ctx)
	diags.Append(computeObjValDiags...)

	computeTypable, ok := t.AttrTypes["compute"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["compute"]))

		return nil, diags
	}

	computeConverted, computeConvertedDiags := computeTypable.ValueFromObject(ctx, computeObjVal)
	diags.Append(computeConvertedDiags...)

	computeVal, ok := computeConverted.(OnboardingStatusComputeValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected to be OnboardingStatusComputeValue, was: %T`, computeConverted))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OnboardingStatusValue{
		Compute: computeVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewOnboardingStatusValueNull() OnboardingStatusValue {
	return OnboardingStatusValue{
		state: attr.ValueStateNull,
	}
}

func NewOnboardingStatusValueUnknown() OnboardingStatusValue {
	return OnboardingStatusValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOnboardingStatusValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OnboardingStatusValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OnboardingStatusValue Attribute Value",
				"While creating a OnboardingStatusValue value, a missing attribute value was detected. "+
					"A OnboardingStatusValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OnboardingStatusValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OnboardingStatusValue Attribute Type",
				"While creating a OnboardingStatusValue value, an invalid attribute value was detected. "+
					"A OnboardingStatusValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OnboardingStatusValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OnboardingStatusValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OnboardingStatusValue Attribute Value",
				"While creating a OnboardingStatusValue value, an extra attribute value was detected. "+
					"A OnboardingStatusValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OnboardingStatusValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOnboardingStatusValueUnknown(), diags
	}

	computeAttribute, ok := attributes["compute"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`compute is missing from object`)

		return NewOnboardingStatusValueUnknown(), diags
	}

	computeVal, ok := computeAttribute.(OnboardingStatusComputeValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected to be OnboardingStatusComputeValue, was: %T`, computeAttribute))
	}

	if diags.HasError() {
		return NewOnboardingStatusValueUnknown(), diags
	}

	return OnboardingStatusValue{
		Compute: computeVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewOnboardingStatusValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OnboardingStatusValue {
	object, diags := NewOnboardingStatusValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOnboardingStatusValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OnboardingStatusType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOnboardingStatusValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOnboardingStatusValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOnboardingStatusValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOnboardingStatusValueMust(OnboardingStatusValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OnboardingStatusType) ValueType(ctx context.Context) attr.Value {
	return OnboardingStatusValue{}
}

var _ basetypes.ObjectValuable = OnboardingStatusValue{}

type OnboardingStatusValue struct {
	Compute OnboardingStatusComputeValue `tfsdk:"compute"`
	state   attr.ValueState
}

func (v OnboardingStatusValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["compute"] = OnboardingStatusComputeType{
		basetypes.ObjectType{
			AttrTypes: OnboardingStatusComputeValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Compute.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["compute"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OnboardingStatusValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OnboardingStatusValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OnboardingStatusValue) String() string {
	return "OnboardingStatusValue"
}

func (v OnboardingStatusValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var compute attr.Value

	{
		compute = v.Compute
	}

	attributeTypes := map[string]attr.Type{
		"compute": OnboardingStatusComputeType{
			basetypes.ObjectType{
				AttrTypes: OnboardingStatusComputeValue{}.AttributeTypes(ctx),
			},
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"compute": compute,
		})

	return objVal, diags
}

func (v OnboardingStatusValue) Equal(o attr.Value) bool {
	other, ok := o.(OnboardingStatusValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Compute.Equal(other.Compute) {
		return false
	}

	return true
}

func (v OnboardingStatusValue) Type(ctx context.Context) attr.Type {
	return OnboardingStatusType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OnboardingStatusValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"compute": OnboardingStatusComputeType{
			basetypes.ObjectType{
				AttrTypes: OnboardingStatusComputeValue{}.AttributeTypes(ctx),
			},
		},
	}
}

var _ basetypes.ObjectTypable = OnboardingStatusComputeType{}

type OnboardingStatusComputeType struct {
	basetypes.ObjectType
}

func (t OnboardingStatusComputeType) Equal(o attr.Type) bool {
	other, ok := o.(OnboardingStatusComputeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OnboardingStatusComputeType) String() string {
	return "OnboardingStatusComputeType"
}

func (t OnboardingStatusComputeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewOnboardingStatusComputeValueNull(), diags
	}

	if in.IsUnknown() {
		return NewOnboardingStatusComputeValueUnknown(), diags
	}

	attributes := in.Attributes()

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OnboardingStatusComputeValue{
		Status: statusVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewOnboardingStatusComputeValueNull() OnboardingStatusComputeValue {
	return OnboardingStatusComputeValue{
		state: attr.ValueStateNull,
	}
}

func NewOnboardingStatusComputeValueUnknown() OnboardingStatusComputeValue {
	return OnboardingStatusComputeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOnboardingStatusComputeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OnboardingStatusComputeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OnboardingStatusComputeValue Attribute Value",
				"While creating a OnboardingStatusComputeValue value, a missing attribute value was detected. "+
					"A OnboardingStatusComputeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OnboardingStatusComputeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OnboardingStatusComputeValue Attribute Type",
				"While creating a OnboardingStatusComputeValue value, an invalid attribute value was detected. "+
					"A OnboardingStatusComputeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OnboardingStatusComputeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OnboardingStatusComputeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OnboardingStatusComputeValue Attribute Value",
				"While creating a OnboardingStatusComputeValue value, an extra attribute value was detected. "+
					"A OnboardingStatusComputeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OnboardingStatusComputeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOnboardingStatusComputeValueUnknown(), diags
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewOnboardingStatusComputeValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return NewOnboardingStatusComputeValueUnknown(), diags
	}

	return OnboardingStatusComputeValue{
		Status: statusVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewOnboardingStatusComputeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OnboardingStatusComputeValue {
	object, diags := NewOnboardingStatusComputeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOnboardingStatusComputeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OnboardingStatusComputeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOnboardingStatusComputeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOnboardingStatusComputeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOnboardingStatusComputeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOnboardingStatusComputeValueMust(OnboardingStatusComputeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OnboardingStatusComputeType) ValueType(ctx context.Context) attr.Value {
	return OnboardingStatusComputeValue{}
}

var _ basetypes.ObjectValuable = OnboardingStatusComputeValue{}

type OnboardingStatusComputeValue struct {
	Status basetypes.StringValue `tfsdk:"status"`
	state  attr.ValueState
}

func (v OnboardingStatusComputeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OnboardingStatusComputeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OnboardingStatusComputeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OnboardingStatusComputeValue) String() string {
	return "OnboardingStatusComputeValue"
}

func (v OnboardingStatusComputeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"status": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"status": v.Status,
		})

	return objVal, diags
}

func (v OnboardingStatusComputeValue) Equal(o attr.Value) bool {
	other, ok := o.(OnboardingStatusComputeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	return true
}

func (v OnboardingStatusComputeValue) Type(ctx context.Context) attr.Type {
	return OnboardingStatusComputeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OnboardingStatusComputeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"status": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = SavingsTotalsType{}

type SavingsTotalsType struct {
	basetypes.ObjectType
}

func (t SavingsTotalsType) Equal(o attr.Type) bool {
	other, ok := o.(SavingsTotalsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SavingsTotalsType) String() string {
	return "SavingsTotalsType"
}

func (t SavingsTotalsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewSavingsTotalsValueNull(), diags
	}

	if in.IsUnknown() {
		return NewSavingsTotalsValueUnknown(), diags
	}

	attributes := in.Attributes()

	computeAttribute, ok := attributes["compute"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`compute is missing from object`)

		return nil, diags
	}

	computeValuable, ok := computeAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected to be basetypes.ObjectValuable, was: %T`, computeAttribute))

		return nil, diags
	}

	computeObjVal, computeObjValDiags := computeValuable.ToObjectValue(ctx)
	diags.Append(computeObjValDiags...)

	computeTypable, ok := t.AttrTypes["compute"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["compute"]))

		return nil, diags
	}

	computeConverted, computeConvertedDiags := computeTypable.ValueFromObject(ctx, computeObjVal)
	diags.Append(computeConvertedDiags...)

	computeVal, ok := computeConverted.(SavingsTotalsComputeValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected to be SavingsTotalsComputeValue, was: %T`, computeConverted))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SavingsTotalsValue{
		Compute: computeVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewSavingsTotalsValueNull() SavingsTotalsValue {
	return SavingsTotalsValue{
		state: attr.ValueStateNull,
	}
}

func NewSavingsTotalsValueUnknown() SavingsTotalsValue {
	return SavingsTotalsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSavingsTotalsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SavingsTotalsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SavingsTotalsValue Attribute Value",
				"While creating a SavingsTotalsValue value, a missing attribute value was detected. "+
					"A SavingsTotalsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SavingsTotalsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SavingsTotalsValue Attribute Type",
				"While creating a SavingsTotalsValue value, an invalid attribute value was detected. "+
					"A SavingsTotalsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SavingsTotalsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SavingsTotalsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SavingsTotalsValue Attribute Value",
				"While creating a SavingsTotalsValue value, an extra attribute value was detected. "+
					"A SavingsTotalsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SavingsTotalsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSavingsTotalsValueUnknown(), diags
	}

	computeAttribute, ok := attributes["compute"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`compute is missing from object`)

		return NewSavingsTotalsValueUnknown(), diags
	}

	computeVal, ok := computeAttribute.(SavingsTotalsComputeValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`compute expected to be SavingsTotalsComputeValue, was: %T`, computeAttribute))
	}

	if diags.HasError() {
		return NewSavingsTotalsValueUnknown(), diags
	}

	return SavingsTotalsValue{
		Compute: computeVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewSavingsTotalsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SavingsTotalsValue {
	object, diags := NewSavingsTotalsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSavingsTotalsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SavingsTotalsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSavingsTotalsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSavingsTotalsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSavingsTotalsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSavingsTotalsValueMust(SavingsTotalsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SavingsTotalsType) ValueType(ctx context.Context) attr.Value {
	return SavingsTotalsValue{}
}

var _ basetypes.ObjectValuable = SavingsTotalsValue{}

type SavingsTotalsValue struct {
	Compute SavingsTotalsComputeValue `tfsdk:"compute"`
	state   attr.ValueState
}

func (v SavingsTotalsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["compute"] = SavingsTotalsComputeType{
		basetypes.ObjectType{
			AttrTypes: SavingsTotalsComputeValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Compute.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["compute"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SavingsTotalsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SavingsTotalsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SavingsTotalsValue) String() string {
	return "SavingsTotalsValue"
}

func (v SavingsTotalsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var compute attr.Value

	{
		compute = v.Compute
	}

	attributeTypes := map[string]attr.Type{
		"compute": SavingsTotalsComputeType{
			basetypes.ObjectType{
				AttrTypes: SavingsTotalsComputeValue{}.AttributeTypes(ctx),
			},
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"compute": compute,
		})

	return objVal, diags
}

func (v SavingsTotalsValue) Equal(o attr.Value) bool {
	other, ok := o.(SavingsTotalsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Compute.Equal(other.Compute) {
		return false
	}

	return true
}

func (v SavingsTotalsValue) Type(ctx context.Context) attr.Type {
	return SavingsTotalsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SavingsTotalsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"compute": SavingsTotalsComputeType{
			basetypes.ObjectType{
				AttrTypes: SavingsTotalsComputeValue{}.AttributeTypes(ctx),
			},
		},
	}
}

var _ basetypes.ObjectTypable = SavingsTotalsComputeType{}

type SavingsTotalsComputeType struct {
	basetypes.ObjectType
}

func (t SavingsTotalsComputeType) Equal(o attr.Type) bool {
	other, ok := o.(SavingsTotalsComputeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SavingsTotalsComputeType) String() string {
	return "SavingsTotalsComputeType"
}

func (t SavingsTotalsComputeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewSavingsTotalsComputeValueNull(), diags
	}

	if in.IsUnknown() {
		return NewSavingsTotalsComputeValueUnknown(), diags
	}

	attributes := in.Attributes()

	lifetimeAttribute, ok := attributes["lifetime"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lifetime is missing from object`)

		return nil, diags
	}

	lifetimeValuable, ok := lifetimeAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lifetime expected to be basetypes.ObjectValuable, was: %T`, lifetimeAttribute))

		return nil, diags
	}

	lifetimeObjVal, lifetimeObjValDiags := lifetimeValuable.ToObjectValue(ctx)
	diags.Append(lifetimeObjValDiags...)

	lifetimeTypable, ok := t.AttrTypes["lifetime"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lifetime expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["lifetime"]))

		return nil, diags
	}

	lifetimeConverted, lifetimeConvertedDiags := lifetimeTypable.ValueFromObject(ctx, lifetimeObjVal)
	diags.Append(lifetimeConvertedDiags...)

	lifetimeVal, ok := lifetimeConverted.(LifetimeValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lifetime expected to be LifetimeValue, was: %T`, lifetimeConverted))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SavingsTotalsComputeValue{
		Lifetime: lifetimeVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewSavingsTotalsComputeValueNull() SavingsTotalsComputeValue {
	return SavingsTotalsComputeValue{
		state: attr.ValueStateNull,
	}
}

func NewSavingsTotalsComputeValueUnknown() SavingsTotalsComputeValue {
	return SavingsTotalsComputeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSavingsTotalsComputeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SavingsTotalsComputeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SavingsTotalsComputeValue Attribute Value",
				"While creating a SavingsTotalsComputeValue value, a missing attribute value was detected. "+
					"A SavingsTotalsComputeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SavingsTotalsComputeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SavingsTotalsComputeValue Attribute Type",
				"While creating a SavingsTotalsComputeValue value, an invalid attribute value was detected. "+
					"A SavingsTotalsComputeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SavingsTotalsComputeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SavingsTotalsComputeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SavingsTotalsComputeValue Attribute Value",
				"While creating a SavingsTotalsComputeValue value, an extra attribute value was detected. "+
					"A SavingsTotalsComputeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SavingsTotalsComputeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSavingsTotalsComputeValueUnknown(), diags
	}

	lifetimeAttribute, ok := attributes["lifetime"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`lifetime is missing from object`)

		return NewSavingsTotalsComputeValueUnknown(), diags
	}

	lifetimeVal, ok := lifetimeAttribute.(LifetimeValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`lifetime expected to be LifetimeValue, was: %T`, lifetimeAttribute))
	}

	if diags.HasError() {
		return NewSavingsTotalsComputeValueUnknown(), diags
	}

	return SavingsTotalsComputeValue{
		Lifetime: lifetimeVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewSavingsTotalsComputeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SavingsTotalsComputeValue {
	object, diags := NewSavingsTotalsComputeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSavingsTotalsComputeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SavingsTotalsComputeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSavingsTotalsComputeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSavingsTotalsComputeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSavingsTotalsComputeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSavingsTotalsComputeValueMust(SavingsTotalsComputeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SavingsTotalsComputeType) ValueType(ctx context.Context) attr.Value {
	return SavingsTotalsComputeValue{}
}

var _ basetypes.ObjectValuable = SavingsTotalsComputeValue{}

type SavingsTotalsComputeValue struct {
	Lifetime LifetimeValue `tfsdk:"lifetime"`
	state    attr.ValueState
}

func (v SavingsTotalsComputeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["lifetime"] = LifetimeType{
		basetypes.ObjectType{
			AttrTypes: LifetimeValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Lifetime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["lifetime"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SavingsTotalsComputeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SavingsTotalsComputeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SavingsTotalsComputeValue) String() string {
	return "SavingsTotalsComputeValue"
}

func (v SavingsTotalsComputeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var lifetime attr.Value

	{
		lifetime = v.Lifetime
	}

	attributeTypes := map[string]attr.Type{
		"lifetime": LifetimeType{
			basetypes.ObjectType{
				AttrTypes: LifetimeValue{}.AttributeTypes(ctx),
			},
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"lifetime": lifetime,
		})

	return objVal, diags
}

func (v SavingsTotalsComputeValue) Equal(o attr.Value) bool {
	other, ok := o.(SavingsTotalsComputeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Lifetime.Equal(other.Lifetime) {
		return false
	}

	return true
}

func (v SavingsTotalsComputeValue) Type(ctx context.Context) attr.Type {
	return SavingsTotalsComputeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SavingsTotalsComputeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"lifetime": LifetimeType{
			basetypes.ObjectType{
				AttrTypes: LifetimeValue{}.AttributeTypes(ctx),
			},
		},
	}
}

var _ basetypes.ObjectTypable = LifetimeType{}

type LifetimeType struct {
	basetypes.ObjectType
}

func (t LifetimeType) Equal(o attr.Type) bool {
	other, ok := o.(LifetimeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LifetimeType) String() string {
	return "LifetimeType"
}

func (t LifetimeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewLifetimeValueNull(), diags
	}

	if in.IsUnknown() {
		return NewLifetimeValueUnknown(), diags
	}

	attributes := in.Attributes()

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return nil, diags
	}

	amountVal, ok := amountAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.Float64Value, was: %T`, amountAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return LifetimeValue{
		Amount: amountVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewLifetimeValueNull() LifetimeValue {
	return LifetimeValue{
		state: attr.ValueStateNull,
	}
}

func NewLifetimeValueUnknown() LifetimeValue {
	return LifetimeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLifetimeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LifetimeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LifetimeValue Attribute Value",
				"While creating a LifetimeValue value, a missing attribute value was detected. "+
					"A LifetimeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LifetimeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LifetimeValue Attribute Type",
				"While creating a LifetimeValue value, an invalid attribute value was detected. "+
					"A LifetimeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LifetimeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LifetimeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LifetimeValue Attribute Value",
				"While creating a LifetimeValue value, an extra attribute value was detected. "+
					"A LifetimeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LifetimeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLifetimeValueUnknown(), diags
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return NewLifetimeValueUnknown(), diags
	}

	amountVal, ok := amountAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.Float64Value, was: %T`, amountAttribute))
	}

	if diags.HasError() {
		return NewLifetimeValueUnknown(), diags
	}

	return LifetimeValue{
		Amount: amountVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewLifetimeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LifetimeValue {
	object, diags := NewLifetimeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLifetimeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LifetimeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLifetimeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLifetimeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLifetimeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLifetimeValueMust(LifetimeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LifetimeType) ValueType(ctx context.Context) attr.Value {
	return LifetimeValue{}
}

var _ basetypes.ObjectValuable = LifetimeValue{}

type LifetimeValue struct {
	Amount basetypes.Float64Value `tfsdk:"amount"`
	state  attr.ValueState
}

func (v LifetimeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["amount"] = basetypes.Float64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Amount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["amount"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LifetimeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LifetimeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LifetimeValue) String() string {
	return "LifetimeValue"
}

func (v LifetimeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"amount": basetypes.Float64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"amount": v.Amount,
		})

	return objVal, diags
}

func (v LifetimeValue) Equal(o attr.Value) bool {
	other, ok := o.(LifetimeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Amount.Equal(other.Amount) {
		return false
	}

	return true
}

func (v LifetimeValue) Type(ctx context.Context) attr.Type {
	return LifetimeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LifetimeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"amount": basetypes.Float64Type{},
	}
}

var _ basetypes.ObjectTypable = UsageType{}

type UsageType struct {
	basetypes.ObjectType
}

func (t UsageType) Equal(o attr.Type) bool {
	other, ok := o.(UsageType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UsageType) String() string {
	return "UsageType"
}

func (t UsageType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewUsageValueNull(), diags
	}

	if in.IsUnknown() {
		return NewUsageValueUnknown(), diags
	}

	attributes := in.Attributes()

	metricAttribute, ok := attributes["metric"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`metric is missing from object`)

		return nil, diags
	}

	metricValuable, ok := metricAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`metric expected to be basetypes.ObjectValuable, was: %T`, metricAttribute))

		return nil, diags
	}

	metricObjVal, metricObjValDiags := metricValuable.ToObjectValue(ctx)
	diags.Append(metricObjValDiags...)

	metricTypable, ok := t.AttrTypes["metric"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`metric expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["metric"]))

		return nil, diags
	}

	metricConverted, metricConvertedDiags := metricTypable.ValueFromObject(ctx, metricObjVal)
	diags.Append(metricConvertedDiags...)

	metricVal, ok := metricConverted.(MetricValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`metric expected to be MetricValue, was: %T`, metricConverted))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UsageValue{
		Metric: metricVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewUsageValueNull() UsageValue {
	return UsageValue{
		state: attr.ValueStateNull,
	}
}

func NewUsageValueUnknown() UsageValue {
	return UsageValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUsageValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UsageValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UsageValue Attribute Value",
				"While creating a UsageValue value, a missing attribute value was detected. "+
					"A UsageValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UsageValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UsageValue Attribute Type",
				"While creating a UsageValue value, an invalid attribute value was detected. "+
					"A UsageValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UsageValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UsageValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UsageValue Attribute Value",
				"While creating a UsageValue value, an extra attribute value was detected. "+
					"A UsageValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UsageValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUsageValueUnknown(), diags
	}

	metricAttribute, ok := attributes["metric"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`metric is missing from object`)

		return NewUsageValueUnknown(), diags
	}

	metricVal, ok := metricAttribute.(MetricValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`metric expected to be MetricValue, was: %T`, metricAttribute))
	}

	if diags.HasError() {
		return NewUsageValueUnknown(), diags
	}

	return UsageValue{
		Metric: metricVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewUsageValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UsageValue {
	object, diags := NewUsageValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUsageValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UsageType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUsageValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUsageValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUsageValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUsageValueMust(UsageValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UsageType) ValueType(ctx context.Context) attr.Value {
	return UsageValue{}
}

var _ basetypes.ObjectValuable = UsageValue{}

type UsageValue struct {
	Metric MetricValue `tfsdk:"metric"`
	state  attr.ValueState
}

func (v UsageValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["metric"] = MetricType{
		basetypes.ObjectType{
			AttrTypes: MetricValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Metric.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["metric"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UsageValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UsageValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UsageValue) String() string {
	return "UsageValue"
}

func (v UsageValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var metric attr.Value

	{
		metric = v.Metric
	}

	attributeTypes := map[string]attr.Type{
		"metric": MetricType{
			basetypes.ObjectType{
				AttrTypes: MetricValue{}.AttributeTypes(ctx),
			},
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"metric": metric,
		})

	return objVal, diags
}

func (v UsageValue) Equal(o attr.Value) bool {
	other, ok := o.(UsageValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Metric.Equal(other.Metric) {
		return false
	}

	return true
}

func (v UsageValue) Type(ctx context.Context) attr.Type {
	return UsageType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UsageValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"metric": MetricType{
			basetypes.ObjectType{
				AttrTypes: MetricValue{}.AttributeTypes(ctx),
			},
		},
	}
}
