// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package generated

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ExampleDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"summary": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"aws": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"credits": schema.ListNestedAttribute{
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"cost": schema.SingleNestedAttribute{
											Attributes: map[string]schema.Attribute{
												"amount": schema.StringAttribute{
													Computed: true,
												},
												"currency": schema.StringAttribute{
													Computed: true,
												},
											},
											CustomType: CostType{
												ObjectType: types.ObjectType{
													AttrTypes: CostValue{}.AttributeTypes(ctx),
												},
											},
											Computed: true,
										},
										"cost_type": schema.StringAttribute{
											Computed: true,
										},
									},
									CustomType: CreditsType{
										ObjectType: types.ObjectType{
											AttrTypes: CreditsValue{}.AttributeTypes(ctx),
										},
									},
								},
								Computed: true,
							},
						},
						CustomType: AwsType{
							ObjectType: types.ObjectType{
								AttrTypes: AwsValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
					"doit": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"credits": schema.ListNestedAttribute{
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"cost": schema.SingleNestedAttribute{
											Attributes: map[string]schema.Attribute{
												"amount": schema.StringAttribute{
													Computed: true,
												},
												"currency": schema.StringAttribute{
													Computed: true,
												},
											},
											CustomType: CostType{
												ObjectType: types.ObjectType{
													AttrTypes: CostValue{}.AttributeTypes(ctx),
												},
											},
											Computed: true,
										},
										"cost_type": schema.StringAttribute{
											Computed: true,
										},
									},
									CustomType: CreditsType{
										ObjectType: types.ObjectType{
											AttrTypes: CreditsValue{}.AttributeTypes(ctx),
										},
									},
								},
								Computed: true,
							},
						},
						CustomType: DoitType{
							ObjectType: types.ObjectType{
								AttrTypes: DoitValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: SummaryType{
					ObjectType: types.ObjectType{
						AttrTypes: SummaryValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type ExampleModel struct {
	Summary SummaryValue `tfsdk:"summary"`
}

var _ basetypes.ObjectTypable = SummaryType{}

type SummaryType struct {
	basetypes.ObjectType
}

func (t SummaryType) Equal(o attr.Type) bool {
	other, ok := o.(SummaryType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SummaryType) String() string {
	return "SummaryType"
}

func (t SummaryType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewSummaryValueNull(), diags
	}

	if in.IsUnknown() {
		return NewSummaryValueUnknown(), diags
	}

	attributes := in.Attributes()

	awsAttribute, ok := attributes["aws"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`aws is missing from object`)

		return nil, diags
	}

	awsValuable, ok := awsAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`aws expected to be basetypes.ObjectValuable, was: %T`, awsAttribute))

		return nil, diags
	}

	awsObjVal, awsObjValDiags := awsValuable.ToObjectValue(ctx)
	diags.Append(awsObjValDiags...)

	awsTypable, ok := t.AttrTypes["aws"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`aws expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["aws"]))

		return nil, diags
	}

	awsConverted, awsConvertedDiags := awsTypable.ValueFromObject(ctx, awsObjVal)
	diags.Append(awsConvertedDiags...)

	awsVal, ok := awsConverted.(AwsValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`aws expected to be AwsValue, was: %T`, awsConverted))
	}

	doitAttribute, ok := attributes["doit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`doit is missing from object`)

		return nil, diags
	}

	doitValuable, ok := doitAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`doit expected to be basetypes.ObjectValuable, was: %T`, doitAttribute))

		return nil, diags
	}

	doitObjVal, doitObjValDiags := doitValuable.ToObjectValue(ctx)
	diags.Append(doitObjValDiags...)

	doitTypable, ok := t.AttrTypes["doit"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`doit expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["doit"]))

		return nil, diags
	}

	doitConverted, doitConvertedDiags := doitTypable.ValueFromObject(ctx, doitObjVal)
	diags.Append(doitConvertedDiags...)

	doitVal, ok := doitConverted.(DoitValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`doit expected to be DoitValue, was: %T`, doitConverted))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SummaryValue{
		Aws:   awsVal,
		Doit:  doitVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewSummaryValueNull() SummaryValue {
	return SummaryValue{
		state: attr.ValueStateNull,
	}
}

func NewSummaryValueUnknown() SummaryValue {
	return SummaryValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSummaryValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SummaryValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SummaryValue Attribute Value",
				"While creating a SummaryValue value, a missing attribute value was detected. "+
					"A SummaryValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SummaryValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SummaryValue Attribute Type",
				"While creating a SummaryValue value, an invalid attribute value was detected. "+
					"A SummaryValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SummaryValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SummaryValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SummaryValue Attribute Value",
				"While creating a SummaryValue value, an extra attribute value was detected. "+
					"A SummaryValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SummaryValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSummaryValueUnknown(), diags
	}

	awsAttribute, ok := attributes["aws"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`aws is missing from object`)

		return NewSummaryValueUnknown(), diags
	}

	awsVal, ok := awsAttribute.(AwsValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`aws expected to be AwsValue, was: %T`, awsAttribute))
	}

	doitAttribute, ok := attributes["doit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`doit is missing from object`)

		return NewSummaryValueUnknown(), diags
	}

	doitVal, ok := doitAttribute.(DoitValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`doit expected to be DoitValue, was: %T`, doitAttribute))
	}

	if diags.HasError() {
		return NewSummaryValueUnknown(), diags
	}

	return SummaryValue{
		Aws:   awsVal,
		Doit:  doitVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewSummaryValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SummaryValue {
	object, diags := NewSummaryValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSummaryValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SummaryType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSummaryValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSummaryValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSummaryValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSummaryValueMust(SummaryValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SummaryType) ValueType(ctx context.Context) attr.Value {
	return SummaryValue{}
}

var _ basetypes.ObjectValuable = SummaryValue{}

type SummaryValue struct {
	Aws   AwsValue  `tfsdk:"aws"`
	Doit  DoitValue `tfsdk:"doit"`
	state attr.ValueState
}

func (v SummaryValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["aws"] = AwsType{
		basetypes.ObjectType{
			AttrTypes: AwsValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)
	attrTypes["doit"] = DoitType{
		basetypes.ObjectType{
			AttrTypes: DoitValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Aws.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["aws"] = val

		val, err = v.Doit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["doit"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SummaryValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SummaryValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SummaryValue) String() string {
	return "SummaryValue"
}

func (v SummaryValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var aws attr.Value

	{
		aws = v.Aws
	}

	var doit attr.Value

	{
		doit = v.Doit
	}

	attributeTypes := map[string]attr.Type{
		"aws": AwsType{
			basetypes.ObjectType{
				AttrTypes: AwsValue{}.AttributeTypes(ctx),
			},
		},
		"doit": DoitType{
			basetypes.ObjectType{
				AttrTypes: DoitValue{}.AttributeTypes(ctx),
			},
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"aws":  aws,
			"doit": doit,
		})

	return objVal, diags
}

func (v SummaryValue) Equal(o attr.Value) bool {
	other, ok := o.(SummaryValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Aws.Equal(other.Aws) {
		return false
	}

	if !v.Doit.Equal(other.Doit) {
		return false
	}

	return true
}

func (v SummaryValue) Type(ctx context.Context) attr.Type {
	return SummaryType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SummaryValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"aws": AwsType{
			basetypes.ObjectType{
				AttrTypes: AwsValue{}.AttributeTypes(ctx),
			},
		},
		"doit": DoitType{
			basetypes.ObjectType{
				AttrTypes: DoitValue{}.AttributeTypes(ctx),
			},
		},
	}
}

var _ basetypes.ObjectTypable = AwsType{}

type AwsType struct {
	basetypes.ObjectType
}

func (t AwsType) Equal(o attr.Type) bool {
	other, ok := o.(AwsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AwsType) String() string {
	return "AwsType"
}

func (t AwsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewAwsValueNull(), diags
	}

	if in.IsUnknown() {
		return NewAwsValueUnknown(), diags
	}

	attributes := in.Attributes()

	creditsAttribute, ok := attributes["credits"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`credits is missing from object`)

		return nil, diags
	}

	creditsVal, ok := creditsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`credits expected to be basetypes.ListValue, was: %T`, creditsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AwsValue{
		Credits: creditsVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewAwsValueNull() AwsValue {
	return AwsValue{
		state: attr.ValueStateNull,
	}
}

func NewAwsValueUnknown() AwsValue {
	return AwsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAwsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AwsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AwsValue Attribute Value",
				"While creating a AwsValue value, a missing attribute value was detected. "+
					"A AwsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AwsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AwsValue Attribute Type",
				"While creating a AwsValue value, an invalid attribute value was detected. "+
					"A AwsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AwsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AwsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AwsValue Attribute Value",
				"While creating a AwsValue value, an extra attribute value was detected. "+
					"A AwsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AwsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAwsValueUnknown(), diags
	}

	creditsAttribute, ok := attributes["credits"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`credits is missing from object`)

		return NewAwsValueUnknown(), diags
	}

	creditsVal, ok := creditsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`credits expected to be basetypes.ListValue, was: %T`, creditsAttribute))
	}

	if diags.HasError() {
		return NewAwsValueUnknown(), diags
	}

	return AwsValue{
		Credits: creditsVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewAwsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AwsValue {
	object, diags := NewAwsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAwsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AwsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAwsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAwsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAwsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAwsValueMust(AwsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AwsType) ValueType(ctx context.Context) attr.Value {
	return AwsValue{}
}

var _ basetypes.ObjectValuable = AwsValue{}

type AwsValue struct {
	Credits basetypes.ListValue `tfsdk:"credits"`
	state   attr.ValueState
}

func (v AwsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["credits"] = basetypes.ListType{
		ElemType: CreditsValue{}.Type(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Credits.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["credits"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AwsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AwsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AwsValue) String() string {
	return "AwsValue"
}

func (v AwsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var credits attr.Value

	{
		credits = v.Credits
	}

	attributeTypes := map[string]attr.Type{
		"credits": basetypes.ListType{
			ElemType: CreditsValue{}.Type(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"credits": credits,
		})

	return objVal, diags
}

func (v AwsValue) Equal(o attr.Value) bool {
	other, ok := o.(AwsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Credits.Equal(other.Credits) {
		return false
	}

	return true
}

func (v AwsValue) Type(ctx context.Context) attr.Type {
	return AwsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AwsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"credits": basetypes.ListType{
			ElemType: CreditsValue{}.Type(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = CreditsType{}

type CreditsType struct {
	basetypes.ObjectType
}

func (t CreditsType) Equal(o attr.Type) bool {
	other, ok := o.(CreditsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CreditsType) String() string {
	return "CreditsType"
}

func (t CreditsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewCreditsValueNull(), diags
	}

	if in.IsUnknown() {
		return NewCreditsValueUnknown(), diags
	}

	attributes := in.Attributes()

	costAttribute, ok := attributes["cost"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost is missing from object`)

		return nil, diags
	}

	costValuable, ok := costAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost expected to be basetypes.ObjectValuable, was: %T`, costAttribute))

		return nil, diags
	}

	costObjVal, costObjValDiags := costValuable.ToObjectValue(ctx)
	diags.Append(costObjValDiags...)

	costTypable, ok := t.AttrTypes["cost"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["cost"]))

		return nil, diags
	}

	costConverted, costConvertedDiags := costTypable.ValueFromObject(ctx, costObjVal)
	diags.Append(costConvertedDiags...)

	costVal, ok := costConverted.(CostValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost expected to be CostValue, was: %T`, costConverted))
	}

	costTypeAttribute, ok := attributes["cost_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost_type is missing from object`)

		return nil, diags
	}

	costTypeVal, ok := costTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost_type expected to be basetypes.StringValue, was: %T`, costTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CreditsValue{
		Cost:     costVal,
		CostType: costTypeVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewCreditsValueNull() CreditsValue {
	return CreditsValue{
		state: attr.ValueStateNull,
	}
}

func NewCreditsValueUnknown() CreditsValue {
	return CreditsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCreditsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CreditsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CreditsValue Attribute Value",
				"While creating a CreditsValue value, a missing attribute value was detected. "+
					"A CreditsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CreditsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CreditsValue Attribute Type",
				"While creating a CreditsValue value, an invalid attribute value was detected. "+
					"A CreditsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CreditsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CreditsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CreditsValue Attribute Value",
				"While creating a CreditsValue value, an extra attribute value was detected. "+
					"A CreditsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CreditsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCreditsValueUnknown(), diags
	}

	costAttribute, ok := attributes["cost"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost is missing from object`)

		return NewCreditsValueUnknown(), diags
	}

	costVal, ok := costAttribute.(CostValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost expected to be CostValue, was: %T`, costAttribute))
	}

	costTypeAttribute, ok := attributes["cost_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost_type is missing from object`)

		return NewCreditsValueUnknown(), diags
	}

	costTypeVal, ok := costTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost_type expected to be basetypes.StringValue, was: %T`, costTypeAttribute))
	}

	if diags.HasError() {
		return NewCreditsValueUnknown(), diags
	}

	return CreditsValue{
		Cost:     costVal,
		CostType: costTypeVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewCreditsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CreditsValue {
	object, diags := NewCreditsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCreditsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CreditsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCreditsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCreditsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCreditsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCreditsValueMust(CreditsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CreditsType) ValueType(ctx context.Context) attr.Value {
	return CreditsValue{}
}

var _ basetypes.ObjectValuable = CreditsValue{}

type CreditsValue struct {
	Cost     CostValue             `tfsdk:"cost"`
	CostType basetypes.StringValue `tfsdk:"cost_type"`
	state    attr.ValueState
}

func (v CreditsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["cost"] = CostType{
		basetypes.ObjectType{
			AttrTypes: CostValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)
	attrTypes["cost_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Cost.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cost"] = val

		val, err = v.CostType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cost_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CreditsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CreditsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CreditsValue) String() string {
	return "CreditsValue"
}

func (v CreditsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var cost attr.Value

	{
		cost = v.Cost
	}

	attributeTypes := map[string]attr.Type{
		"cost": CostType{
			basetypes.ObjectType{
				AttrTypes: CostValue{}.AttributeTypes(ctx),
			},
		},
		"cost_type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"cost":      cost,
			"cost_type": v.CostType,
		})

	return objVal, diags
}

func (v CreditsValue) Equal(o attr.Value) bool {
	other, ok := o.(CreditsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Cost.Equal(other.Cost) {
		return false
	}

	if !v.CostType.Equal(other.CostType) {
		return false
	}

	return true
}

func (v CreditsValue) Type(ctx context.Context) attr.Type {
	return CreditsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CreditsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"cost": CostType{
			basetypes.ObjectType{
				AttrTypes: CostValue{}.AttributeTypes(ctx),
			},
		},
		"cost_type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = CostType{}

type CostType struct {
	basetypes.ObjectType
}

func (t CostType) Equal(o attr.Type) bool {
	other, ok := o.(CostType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CostType) String() string {
	return "CostType"
}

func (t CostType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewCostValueNull(), diags
	}

	if in.IsUnknown() {
		return NewCostValueUnknown(), diags
	}

	attributes := in.Attributes()

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return nil, diags
	}

	amountVal, ok := amountAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.StringValue, was: %T`, amountAttribute))
	}

	currencyAttribute, ok := attributes["currency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`currency is missing from object`)

		return nil, diags
	}

	currencyVal, ok := currencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`currency expected to be basetypes.StringValue, was: %T`, currencyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CostValue{
		Amount:   amountVal,
		Currency: currencyVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewCostValueNull() CostValue {
	return CostValue{
		state: attr.ValueStateNull,
	}
}

func NewCostValueUnknown() CostValue {
	return CostValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCostValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CostValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CostValue Attribute Value",
				"While creating a CostValue value, a missing attribute value was detected. "+
					"A CostValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CostValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CostValue Attribute Type",
				"While creating a CostValue value, an invalid attribute value was detected. "+
					"A CostValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CostValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CostValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CostValue Attribute Value",
				"While creating a CostValue value, an extra attribute value was detected. "+
					"A CostValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CostValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCostValueUnknown(), diags
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return NewCostValueUnknown(), diags
	}

	amountVal, ok := amountAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.StringValue, was: %T`, amountAttribute))
	}

	currencyAttribute, ok := attributes["currency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`currency is missing from object`)

		return NewCostValueUnknown(), diags
	}

	currencyVal, ok := currencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`currency expected to be basetypes.StringValue, was: %T`, currencyAttribute))
	}

	if diags.HasError() {
		return NewCostValueUnknown(), diags
	}

	return CostValue{
		Amount:   amountVal,
		Currency: currencyVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewCostValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CostValue {
	object, diags := NewCostValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCostValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CostType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCostValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCostValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCostValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCostValueMust(CostValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CostType) ValueType(ctx context.Context) attr.Value {
	return CostValue{}
}

var _ basetypes.ObjectValuable = CostValue{}

type CostValue struct {
	Amount   basetypes.StringValue `tfsdk:"amount"`
	Currency basetypes.StringValue `tfsdk:"currency"`
	state    attr.ValueState
}

func (v CostValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["amount"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["currency"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Amount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["amount"] = val

		val, err = v.Currency.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["currency"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CostValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CostValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CostValue) String() string {
	return "CostValue"
}

func (v CostValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"amount":   basetypes.StringType{},
		"currency": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"amount":   v.Amount,
			"currency": v.Currency,
		})

	return objVal, diags
}

func (v CostValue) Equal(o attr.Value) bool {
	other, ok := o.(CostValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Amount.Equal(other.Amount) {
		return false
	}

	if !v.Currency.Equal(other.Currency) {
		return false
	}

	return true
}

func (v CostValue) Type(ctx context.Context) attr.Type {
	return CostType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CostValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"amount":   basetypes.StringType{},
		"currency": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = DoitType{}

type DoitType struct {
	basetypes.ObjectType
}

func (t DoitType) Equal(o attr.Type) bool {
	other, ok := o.(DoitType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DoitType) String() string {
	return "DoitType"
}

func (t DoitType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewDoitValueNull(), diags
	}

	if in.IsUnknown() {
		return NewDoitValueUnknown(), diags
	}

	attributes := in.Attributes()

	creditsAttribute, ok := attributes["credits"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`credits is missing from object`)

		return nil, diags
	}

	creditsVal, ok := creditsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`credits expected to be basetypes.ListValue, was: %T`, creditsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DoitValue{
		Credits: creditsVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewDoitValueNull() DoitValue {
	return DoitValue{
		state: attr.ValueStateNull,
	}
}

func NewDoitValueUnknown() DoitValue {
	return DoitValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDoitValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DoitValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DoitValue Attribute Value",
				"While creating a DoitValue value, a missing attribute value was detected. "+
					"A DoitValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DoitValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DoitValue Attribute Type",
				"While creating a DoitValue value, an invalid attribute value was detected. "+
					"A DoitValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DoitValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DoitValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DoitValue Attribute Value",
				"While creating a DoitValue value, an extra attribute value was detected. "+
					"A DoitValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DoitValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDoitValueUnknown(), diags
	}

	creditsAttribute, ok := attributes["credits"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`credits is missing from object`)

		return NewDoitValueUnknown(), diags
	}

	creditsVal, ok := creditsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`credits expected to be basetypes.ListValue, was: %T`, creditsAttribute))
	}

	if diags.HasError() {
		return NewDoitValueUnknown(), diags
	}

	return DoitValue{
		Credits: creditsVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewDoitValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DoitValue {
	object, diags := NewDoitValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDoitValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DoitType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDoitValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDoitValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDoitValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDoitValueMust(DoitValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DoitType) ValueType(ctx context.Context) attr.Value {
	return DoitValue{}
}

var _ basetypes.ObjectValuable = DoitValue{}

type DoitValue struct {
	Credits basetypes.ListValue `tfsdk:"credits"`
	state   attr.ValueState
}

func (v DoitValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["credits"] = basetypes.ListType{
		ElemType: CreditsValue{}.Type(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Credits.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["credits"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DoitValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DoitValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DoitValue) String() string {
	return "DoitValue"
}

func (v DoitValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var credits attr.Value

	{
		credits = v.Credits
	}

	attributeTypes := map[string]attr.Type{
		"credits": basetypes.ListType{
			ElemType: CreditsValue{}.Type(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"credits": credits,
		})

	return objVal, diags
}

func (v DoitValue) Equal(o attr.Value) bool {
	other, ok := o.(DoitValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Credits.Equal(other.Credits) {
		return false
	}

	return true
}

func (v DoitValue) Type(ctx context.Context) attr.Type {
	return DoitType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DoitValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"credits": basetypes.ListType{
			ElemType: CreditsValue{}.Type(ctx),
		},
	}
}
